### vars
[String] $url
[String] $hql = "select tbl.id as id, tbl.fullName as fullName from com.msp.dao.entities.User tbl "
[String] $username
[String] $secFilePath
[SecureString] $password = Get-Content $secFilePath | ConvertTo-SecureString

### object to show types
#$proxy = New-WebServiceProxy -Uri:$url -UseDefaultCredential
#$typeName = $proxy.GetType()
#$proxyAssembly = [AppDomain]::CurrentDomain.GetAssemblies() | Where-Object {$_.GetType($typeName)}
#$proxyAssembly.ExportedTypes | Select Name | Sort

[pscredential] $creds = new-object -TypeName pscredential($username,$password)

### object to execute methods
$webservicex = New-WebServiceProxy -Verbose -Uri $url -Credential $creds #-UseDefaultCredential #-namespace WebServiceProxy -Class executeHQL
#$webservicex.PreAuthenticate
[Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1lm_prdmsp_icc_corp_MSP_WS_wsdl.InvokeOperationMessageResponse] $response = $webservicex.executeHQL($hql) #.BeginexecuteHQL($hql,$cb, $asyncState)
$response
